Slava viz in elsa
dataforgoodfr/batch11_e_cartomobile pull request #37
Opened 2023-06-26 03:48 UTC by slightlym

There are two files modified:
1. (new): file for the transformation of the World and Europe EV data uploaded with the previous commit
2. Elsa's plotly file into which I added the code for the graphs on the World and Europe EV registrations. While the code itself should be correct, not sure I did it properly. Elsa is adding her visualizations as programs (and no idea where they are called) while I introduce mine directly.

Please don't hesitate to comment and advise.

2023-06-26 09:39 UTC, BastienGauthier requested changes
Je pense que tu peux refaire une passe en transformant le code que tu as ajouté en fonction, pour garder le côté modulaire.
Je t'ai mis le détail par fichier dans la review.

2023-06-26 09:39 UTC, BastienGauthier commented on e_cartomobile/data_transform/data_world_graphs.py
Je pense qu'il faudrait plutôt faire une fonction telle que : 
def get_ev_evolution(region : str) -> pd.DataFrame

Et l'appeler avec df_w = get_ev_evolution("World") typiquement dans le visualization_plotly.py

2023-06-26 09:39 UTC, BastienGauthier commented on e_cartomobile/data_analytics/vizualisation_plotly.py
Il faut faire des fonctions que tu appelles dans la page qui va bien (app.py en l'occurence)

Ici, le code va tourner dans le vide (et crasher d'ailleurs je pense comme tu ne définis pas df_eu.) As-tu testé le code en situation ? J'ai l'impression que ça vient d'un notebook externe, ce qui est très bien pour mettre en place, mais ne dispense pas de vérifier l'applicabilité derrière.

2023-06-26 19:34 UTC, slightlym commented on e_cartomobile/data_analytics/vizualisation_plotly.py
Effectivement, le code a été testé dans un notebook externe, et uniquement pour les données mondiales. Sinon, c'est quoi la bonne pratique de le tester?

2023-06-26 19:47 UTC, BastienGauthier commented on e_cartomobile/data_analytics/vizualisation_plotly.py
Si tu as bien configuré ton environnement (au sens du ReadMe du repo : https://github.com/dataforgoodfr/batch11_e_cartomobile#readme ), normalement tu peux faire tourner :
"poetry run streamlit run app.py" dans le répertoire principal du projet, avec une console standard ou un miniconda, selon ton installation.

2023-06-26 21:49 UTC, slightlym commented on e_cartomobile/data_analytics/vizualisation_plotly.py
Tout à l'heure je pouvais lancer le streamlit mais les graphs n'étaient pas construits car j'utilisais une branche où il n'y avait pas de données que j'avais poussé auparavant.
Maintenant j'ai synchronisé pour avoir les données. En revanche, je reçois l'erreur "No module named 'psycopg2'" et je n'ai aucune idée de ce que c'est. Je crois pourtant avoir créé la branche actuelle (slava_viz_v4) à partir de main, donc tout devrait être à jour, non?

2023-06-27 05:28 UTC, BastienGauthier commented on e_cartomobile/data_analytics/vizualisation_plotly.py
L'erreur est assez explicite : tu n'as pas le module psycopg2 (qui sert pour requêter la base de données). 
Tu peux faire un nouveau "poetry install" pour te mettre à jour des librairies utilisées par exemple.
D'ailleurs, pour le test tu devras peut-être commenter les graphes des autres tab de la page qui utilisent des requêtes en base de données, ça serait un peu plus compliqué de mettre en place la configuration pour ça !

2023-06-27 16:15 UTC, slightlym commented on e_cartomobile/data_analytics/vizualisation_plotly.py
En lisant cela, je me souviens d'une vieille blague soviétique: "maman, à qui tu viens de parler?"
Bref, j'ai rien compris. :-)
`poetry install` - il faut le faire après avoir activé l'environnnement virtuel? Et où? Peu importe / dans le dossier du projet / ailleurs? J'ai essayé d'activer l'environnement virtuel et enchaîné directement mais reçu le message d'erreur: "Poetry could not find a pyproject.toml file in C:\Users\jklim or its parents"
Le deuxième paragraphe de ton message, j'en parle même pas.
J'en profite pour te dire un énorme merci de ta patience!

2023-06-29 17:09 UTC, BastienGauthier commented on e_cartomobile/data_analytics/vizualisation_plotly.py
Le poetry install, tu dois le faire là où le poetry.lock est, soit à la racine du projet, après avoir activé l'environnement virtuel. S'il ne trouve pas poetry, tu peux faire un "pip install poetry" avant !
Pour le deuxième paragraphe, on verra après :P

2023-08-17 09:33 UTC, closed without merging